RPC_SERVER_HOST = 'backend_server'
RPC_SERVER_PORT = 4040

NEWS_TABLE_NAME = "news"
NEWS_LIST_BATCH_SIZE = 10
NEWS_LIMIT = 200
USER_NEWS_TIME_OUT_IN_SECONDS = 60

REDIS_HOST = 'redis'
REDIS_PORT = 6379

MONGO_DB_HOST = 'mongodb'
MONGO_DB_PORT = '27017'

NEWS_RECOMMENDER_HOST = 'news_recommender'
NEWS_RECOMMENDER_PORT = '5050'

LOG_CLICKS_TASK_QUEUE_URL = 'amqp://wnaagfbf:X-xeVV-tE22PUjnE6_IO1pJ66w6TKWak@emu.rmq.cloudamqp.com/wnaagfbf'
LOG_CLICKS_TASK_QUEUE_NAME = 'tap_news_log_clicks_task_queue'
